name: Android CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, 'feat/**', 'fix/**', 'chore/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Inject secrets to Gradle properties
        shell: bash
        run: |
          mkdir -p ~/.gradle
          {
            echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}"
            echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}"
            echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}"
            echo "NAVER_APP_NAME=${{ secrets.NAVER_APP_NAME }}"
            echo "GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}"
            echo "BASE_URL=${{ secrets.BASE_URL }}"
          } >> ~/.gradle/gradle.properties
          test -f ~/.gradle/gradle.properties && echo "gradle.properties injected."

      - name: Build
        run: ./gradlew clean build -x test --no-daemon
