name: Android CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, 'feat/**', 'fix/**', 'chore/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew clean build -x test --no-daemon
      # 테스트도 돌릴 거면 위 -x test 제거